path: /Users/jan/Documents/code/cv/project
train: /Users/jan/Documents/code/cv/project/train_img
val: /Users/jan/Documents/code/cv/project/test_img

nc: 16

# Classes
names:
  0: abudefduf vaigiensis
  1: acanthurus nigrofuscus
  2: amphiprion clarkii
  3: chaetodon lununatus
  4: chaetodon speculum
  5: chaetodon trifascialis
  6: chromis chrysura
  7: dascyllus aruanus
  8: dascyllus reticulatus
  9: hemigumnus malapterus
  10: myripristis kuntee
  11: neoglyphidodon nigroris
  12: pempheris vanicolensis
  13: plectrogly-phidodon dickii
  14: zebrasoma scopas
  15: unknown

# Augmentation settings
augmentations:
  fliplr: 0.5  # 50% chance to flip images left-right
  flipud: 0.2  # 20% chance to flip images up-down
  scale: 0.1   # Scale images by +/- 10%
  translate: 0.1  # Translate images by +/- 10% of image dimensions
  rotate: 5  # Rotate images by +/- 5 degrees
  shear: 5  # Shear images by +/- 5 degrees
  perspective: 0.05  # Apply perspective transformation with a probability
  mosaic: 0.75  # 75% chance to apply mosaic augmentation
  mixup: 0.4  # 40% chance to apply mixup augmentation