path: /home/jan/Documents/code/CV-Fish-Abundance/
train: ./txt/train_img.txt
val: ./txt/val_img.txt
test: ./txt/test_img.txt

nc: 16

# Classes
names:
  0: abudefduf vaigiensis
  1: acanthurus nigrofuscus
  2: amphiprion clarkii
  3: chaetodon lununatus
  4: chaetodon speculum
  5: chaetodon trifascialis
  6: chromis chrysura
  7: dascyllus aruanus
  8: dascyllus reticulatus
  9: hemigumnus malapterus
  10: myripristis kuntee
  11: neoglyphidodon nigroris
  12: pempheris vanicolensis
  13: plectrogly-phidodon dickii
  14: zebrasoma scopas
  15: unknown